schema: 
    - "data/schema.graphql"
    - "data/relay.graphql"
documents: "src/**/*.{graphql, ts,tsx}"
extensions:
    endpoints:
        default:
            url: https://tmdb.apps.quintero.io
    languageService:
        useSchemaFileDefinitions: true